AWS_ACCESS_KEY: "INSERT AWS ACCESS KEY"
AWS_SECRET_KEY: "INSERT AWS SECRET KEY"
AWS_REGION: "INSERT AWS REGION"
AWS_BUCKET: "INSERT AWS BUCKET"
AWS_ENDPOINT: "INSERT AWS ENDPOINT"
SKIP_RAILS_ADMIN_INITIALIZER: "SET SKIP"
